version: '3.8'

services:
  n8n:
    image: n8n/n8n
    container_name: n8n
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/data/database.sqlite
      - N8N_LOG_LEVEL=info
      - N8N_EDITOR_BASE_URL=http://localhost:5678
    volumes:
      - ./data:/data
    ports:
      - "5678:5678"
    restart: always

networks:
  default:
    driver: bridge

volumes:
  data: